name: Scripts running
on:
  push:
    branches: [master, dev, test]
  pull_request:
    branches: [master, dev, test]
jobs:
  scripts-runnig:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node modules
        run: yarn install
      - name: Building project
        run: yarn build
      - name: Linting code
        run: yarn lint
